

using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using HSEBank.scr.Application.Commands;
using HSEBank.scr.Domain.Entities;
using HSEBank.scr.Events;
using HSEBank.scr.Ports;
using FluentAssertions;
using static AutoGeneratedProgram;

namespace HSEBank.Tests.Common;

public sealed class TestLogger : ILogger
{
    public readonly List<string> Lines = new();
    public void Log(string message) => Lines.Add(message);
}

public sealed class SpyHandler<T> : IEventHandler<T> where T : IEvent
{
    public int Calls { get; private set; }
    public readonly List<T> Received = new();
    public void Handle(T ev) { Calls++; Received.Add(ev); }
}

public sealed class FakeRepo<T> : IRepository<T> where T : class
{
    private readonly List<T> _store = new();
    public int GetAllCalls { get; private set; }
    public int GetByIdCalls { get; private set; }

    public void Add(T entity) => _store.Add(entity);
    public void Remove(T entity) => _store.Remove(entity);
    public IEnumerable<T>? GetAll() { GetAllCalls++; return _store; }

    public T GetById(Guid id)
    {
        GetByIdCalls++;
        var prop = typeof(T).GetProperty("Id");
        var val = _store.FirstOrDefault(x => (Guid)(prop!.GetValue(x) ?? Guid.Empty) == id);
        return val ?? throw new InvalidOperationException("not found");
    }

    public void ShouldContainId(Guid id)
    {
        var prop = typeof(T).GetProperty("Id");
        _store.Any(x => (Guid)(prop!.GetValue(x) ?? Guid.Empty) == id).Should().BeTrue();
    }
}

/// Вспомогалки для временных файлов/папок
public static class Temp
{
    public static string Dir()
    {
        var p = Path.Combine(Path.GetTempPath(), "HSEBankTests", Guid.NewGuid().ToString("N"));
        Directory.CreateDirectory(p);
        return p;
    }
    public static string FilePath(string extension = "tmp")
        => Path.Combine(Dir(), $"f_{Guid.NewGuid():N}.{extension}");
}